x<-c(5,10,15,20,25,30)
y<-c(-1,NA,75,3,5,8)
z<-c(5)
xz<-c(x*z)
yz<-c(y*z)
print(xz)
print(yz)
y<-ifelse(is.na(y),2.5,y)
yz<-c(y*z)
print(Assignment_1)
print(state.abb)
apply(Assignment_1, 2, mean)
apply(Assignment_1, 2, median)
# Median murder rate is 6.8
apply(Assignment_1, 2, mean)
colMeans(Assignment_1)
table(Assignment_1)
attach(Assignment_1)
mean(Murder)
NE<-c(CT, MA, MS, NH, RI, VT)
print(mean(Murder))
summary(Murder)
subset(Assignment_1, select = c(VT, RI, NH, MS, MA, CT))
subset(Assignment_1, select = 46,31,30,25,19,7)
subset.matrix(Assignment_1, select = State(CT,MA,MS,NH,RI,VT))
print(median(Murder))
attach(Assignment_1)
mydat<-data.frame(data.set=c("AL", "AK", "AZ", "AR", "CA" ,"CO", "CT", "DE", "FL", "GA"))
print(mydat)
attach(Assignment_1)
print(NE1)
mean(df)
print(xz)
print(yz)
subset.default(NE,State=="CT", State=="MA", State=="VT", State=="RI", State=="ME", State=="NH" )
subNE = subset(Assignment_1,State=="CT" | State=="MA" | State== "ME" | State=="NH" | State=="RI" | State=="VT")
NEdata<-subset(Assignment_1, State=="CT" | State=="MA" | State== "ME" | State=="NH" | State=="RI" | State=="VT")
mean(subNE[["Murder"]])
mean(Assignment_1[["Murder"]])
mean(Assignment_1[["Vcrime"]])
mean(Assignment_1[["Vcrime"]])
median(Assignment_1[["Murder"]])
